name: CI for AI Film Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Script Generation Test
        run: |
          python scripts/generate_script.py
      - name: Run Scene Generation Test
        run: |
          python scenes/generate_scene.py
      - name: Run Character Voice Generation Test
        run: |
          python characters/generate_voice.py
